baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "About Hugo"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    name = "Hugo"
    url = "/hugo/"
    weight = 20

[[menu.main]]
    name = "Examples"
    url = "/examples/"
    weight = 30
 [[menu.main]]
    name = "Themes"
    url = "/themes/"
    weight = 40
 
[[menu.main]]
    name = "Sites"
    url = "/sites/"
    weight = 50






[params]
  mainSections = ['about', 'hugo', 'examples', 'themes', 'sites']

  homepage_button_link = '/hugo'
  homepage_button_text = 'Get Started with Hugo'
  homepage_intro = 'This is shown as long as the homepage has no content'
  homepage_image = 'images/zero.gif'


  
  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "About Hugo is a Website to promote the use of SSGs in IT education."
    meta_og_title = "About Hugo Project"
    meta_og_type = "website"
    meta_og_url = "https://about-hugo.github.io"
    meta_og_image = ""
    meta_og_description = "About Hugo Project/Website by B. Kleinen build with hugo and the Whisper Theme"


  [params.logo]
      mobile = "images/logo-mobile.svg"
      standard  = "images/logo.svg"

  [params.footer]
    copyright_text = '<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://about-hugo.github.io/">About Hugo Project</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://bkleinen.github.io">Barne Kleinen</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""></a></p>'
    #copyright_text = '<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://about-hugo.github.io/">About Hugo Project</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://barnekleinen.de">Barne Kleinen</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""></a></p>'
    #copyright_text = 'Created by <a class="zerostatic" href="https://bkleinen.github.io/contact/">B. Kleinen</a>'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      table = true
      taskList = true
  