baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "About Hugo"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Hugo"
    url = "/hugo/"
    weight = 10

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 40

[[menu.main]]
    name = "A11Y"
    url = "/accessibility/"
    weight = 50





[params]
  google_analytics_id=""
  homepage_button_link = '/hugo'
  homepage_button_text = 'Get Started'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = 'images/zero.gif'

  mainSections = ['docs', 'accessibility', 'hugo']
  
  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "images/logo-mobile.svg"
      standard  = "images/logo.svg"

  [params.footer]
    copyright_text = 'Created by <a class="zerostatic" href="https://bkleinen.github.io/contact/">B. Kleinen</a>'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      table = true
      taskList = true
  